### PR TITLE
ios 7/8 support

### PR DESCRIPTION
**Pull request by AYastrebov**
- downgrade deployment target for ios 7 and 8

### CODE REVIEW

**Comment by AYastrebov** [comment]
@jhurray you need also create a new tag 2.0.2 and update the spec on cocoapods repo

**Comment by jhurray** [comment]
@AYastrebov yep I have a reminder set to do this, I am on my work laptop right now so have to wait until I get home :)

**Comment by jhurray** [comment]
Should see the new tag later tonight

**Comment by AYastrebov** [comment]
@jhurray thanks!

**Comment by jhurray** [comment]
Oh man... I totally forgot! I'll do it tonight haha sorry

**Comment by jhurray** [comment]
@AYastrebov Updated!

**Pull request merged**
