### PR TITLE
Rotation x y z

### PR DESCRIPTION
**Pull request by Biinngg**
Add rotation animation around layer's x y and z axis.

### CODE REVIEW

**Comment by jhurray** [comment]
I'm fine with adding these changes, but I dont think we should delete the `rotate` method. Because this is not a major update I dont want to break anyones code who uses the `rotate` method. Instead maybe maybe just have `rotate` call `rotateX` in its implementation.

**Comment by Biinngg** [comment]
OK, I have added it back.

**Comment by jhurray** [comment]
👍

**Comment by jhurray** [comment]
Merged

**Pull request merged**
